[package]
name = "castle-fight-client"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bevy = { workspace = true, features = ["3d", "png", "ui"] }
castle-fight-sim = { path = "../sim" }
serde.workspace = true
serde_json.workspace = true
